"""Phase-scoped scientific identity for AAA-1K.

AAA-1K is a new versioned research phase, not a continuation of the v2.1
confirmation freeze. Its fingerprint therefore covers *its own* source and the
shared code it actually executes, and nothing else. This is deliberate and it
is the opposite of a convenience exclusion:

* the v2.1 and observation-noise fingerprints are untouched, and their
  historical freezes still describe the trees that produced their evidence;
* adding this package necessarily changes those repository-wide fingerprints,
  because they cover every tracked file. That is the correct behaviour and it
  is recorded in `docs/aaa_1k_handoff.md` rather than worked around by adding
  an exclusion so an old hash keeps matching;
* historical experiments stay reproducible from their historical checkout,
  which is what the annotated phase tags are for.

One hash is not asked to describe two different worlds.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path
from typing import Any

from . import PHASE_VERSION

IDENTITY_SCHEMA = "aaa.1k.scientific_source.v1"

PHASE_PREFIX = "research/aaa_1k/"
SHARED_DEPENDENCIES = (
    "aaa/__init__.py",
    "aaa/config.py",
    "aaa/environment.py",
    "aaa/predictors.py",
)
PHASE_TESTS = ("tests/test_aaa_1k.py",)
PHASE_DOCS = (
    "docs/aaa_charter.md",
    "docs/aaa_1k_architecture.md",
    "docs/aaa_1k_literature_review.md",
    "docs/aaa_1k_decisions.md",
)
DEPENDENCY_LOCK = "requirements-lock.txt"

# Generated by this phase; excluded so committing a result cannot change the
# identity that result records.
GENERATED = (
    "docs/aaa_1k_report.md",
    "docs/aaa_1k_handoff.md",
    "docs/aaa_1k_self_review.md",
)


class PhaseIdentityError(RuntimeError):
    """Raised when the phase source cannot be identified safely."""


def _tracked(root: Path) -> set[str]:
    try:
        output = subprocess.check_output(
            ["git", "-C", str(root), "ls-files", "-z", "--cached"], stderr=subprocess.PIPE
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as error:
        raise PhaseIdentityError("phase identity requires a readable Git repository") from error
    return {name for name in output.decode("utf-8").split("\0") if name}


def phase_files(root: Path) -> list[str]:
    """Every file whose contents can change what an AAA-1K experiment does."""

    tracked = _tracked(root)
    selected = {name for name in tracked if name.startswith(PHASE_PREFIX) and name not in GENERATED}
    selected.update(name for name in SHARED_DEPENDENCIES if name in tracked)
    selected.update(name for name in PHASE_TESTS if name in tracked)
    selected.update(name for name in PHASE_DOCS if name in tracked)
    if DEPENDENCY_LOCK in tracked:
        selected.add(DEPENDENCY_LOCK)
    return sorted(selected)


def phase_fingerprint(project_root: str | Path) -> dict[str, Any]:
    """Hash the phase source. Fails closed on a missing file or a symlink."""

    root = Path(project_root).resolve()
    names = phase_files(root)
    if not names:
        raise PhaseIdentityError("phase source file set is empty")
    files: dict[str, dict[str, Any]] = {}
    for name in names:
        path = root / name
        if path.is_symlink():
            raise PhaseIdentityError(f"phase source contains a symlink: {name}")
        if not path.is_file():
            raise PhaseIdentityError(f"phase source is missing or not a regular file: {name}")
        content = path.read_bytes()
        files[name] = {
            "sha256": hashlib.sha256(content).hexdigest(),
            "bytes": len(content),
        }
    encoded = json.dumps(files, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")
    return {
        "schema": IDENTITY_SCHEMA,
        "phase_version": PHASE_VERSION,
        "sha256": hashlib.sha256(encoded).hexdigest(),
        "file_count": len(files),
        "files": files,
        "excluded_generated": list(GENERATED),
        "scope_note": (
            "this phase's own source, the shared AAA modules it executes, its tests, its "
            "protocol documents and the dependency lock; repository-wide v2.1 and "
            "observation-noise fingerprints are separate and are not modified by this phase"
        ),
    }


def git_provenance(project_root: str | Path) -> dict[str, Any]:
    """Commit, tree and dirty flag, recorded as provenance rather than identity."""

    root = Path(project_root).resolve()

    def run(*args: str) -> str:
        return (
            subprocess.check_output(["git", "-C", str(root), *args], stderr=subprocess.PIPE).decode().strip()
        )

    try:
        return {
            "commit": run("rev-parse", "HEAD"),
            "tree_hash": run("rev-parse", "HEAD^{tree}"),
            "branch": run("rev-parse", "--abbrev-ref", "HEAD"),
            "dirty": bool(run("status", "--porcelain")),
        }
    except (subprocess.CalledProcessError, FileNotFoundError):
        return {"commit": None, "tree_hash": None, "branch": None, "dirty": None}


def lineage_record(
    *,
    model_state_hash: str,
    parameter_count: int,
    initialization_seed: int,
    project_root: str | Path,
    parent_model_id: str | None = None,
    benchmark_version: str = "aaa.1k.benchmarks.v1",
) -> dict[str, Any]:
    """Metadata that lets a future phase treat this model as an ancestor.

    AAA-1K is the root of an experimental lineage, so ``parent_model_id`` is
    ``None``. Nothing here grows, widens or distils a network; this only makes
    sure a later phase that wants to can say exactly what it grew from.
    """

    return {
        "schema": "aaa.1k.lineage.v1",
        "model_format_version": "aaa.1k.gru.v1",
        "architecture_id": "AAA1KGRU-3x16x2",
        "phase_version": PHASE_VERSION,
        "parameter_count": parameter_count,
        "parent_model_id": parent_model_id,
        "is_lineage_root": parent_model_id is None,
        "initialization_seed": initialization_seed,
        "state_hash": model_state_hash,
        "benchmark_version": benchmark_version,
        "source_commit": git_provenance(project_root)["commit"],
        "scientific_fingerprint": phase_fingerprint(project_root)["sha256"],
        "growth_status": "no growth is implemented in this phase; future parameters must be earned",
    }
