"""Write (or ``--check``) the ``aaa.python.v1`` development report from retained stage evidence.

Every number in the report is read from the evidence files under
``docs/evidence/aaa_python_v1/``; nothing is typed by hand. ``--check`` fails
if the committed report differs from what the evidence produces.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "docs/evidence/aaa_python_v1"
REPORT = ROOT / "docs/aaa_python_v1_development_report.md"
FAMILIES = ("syntax", "outcome", "output", "localize", "repair")
STAGES = (
    "encoders",
    "heads",
    "capacity",
    "budget",
    "optimization",
    "tool",
    "adapt",
    "plasticity",
    "posthoc",
    "attack",
)


def load(stage: str) -> dict[str, Any] | None:
    path = EVIDENCE / f"stage_{stage}.json"
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def ci(entry: dict[str, Any]) -> str:
    if entry.get("interval_status") != "MEASURED":
        return f"{entry['mean']:.3f} [n/a]"
    return f"{entry['mean']:.3f} [{entry['lower']:.3f}, {entry['upper']:.3f}]"


def signed(entry: dict[str, Any]) -> str:
    if entry.get("interval_status") != "MEASURED":
        return f"{entry['mean']:+.3f} [n/a]"
    return f"{entry['mean']:+.3f} [{entry['lower']:+.3f}, {entry['upper']:+.3f}]"


def arm_table(stage: dict[str, Any], arms: list[str], mode: str = "frozen") -> list[str]:
    summary = stage["summary"]["arms"]
    out = ["| Arm | Trainable | " + " | ".join(FAMILIES) + " |", "|---|---:|" + "---|" * len(FAMILIES)]
    for arm in arms:
        if arm not in summary:
            continue
        params = stage["arms"].get(arm, {}).get("parameters", {}).get("trainable_parameters", "")
        cells = [ci(summary[arm][f][mode]) if mode in summary[arm].get(f, {}) else "" for f in FAMILIES]
        out.append(f"| `{arm}` | {params} | " + " | ".join(cells) + " |")
    return out


def contrast_table(stage: dict[str, Any], names: list[str] | None = None) -> list[str]:
    contrasts = stage["summary"]["contrasts"]
    out = ["| Contrast | Difference [95%] | Sign | Holm p | Disagreements |", "|---|---|---|---:|---:|"]
    for name, row in contrasts.items():
        if names is not None and not any(n in name for n in names):
            continue
        holm = row.get("holm", {}).get("holm_adjusted_p")
        out.append(
            f"| {name} | {signed(row)} | {row['resolved_sign']} | "
            f"{'' if holm is None else f'{holm:.4f}'} | {row['disagreements']} |"
        )
    return out


def slice_table(stage: dict[str, Any], arms: list[str]) -> list[str]:
    summary = stage["summary"]["arms"]
    slices = ("in_distribution", "novel_literals", "novel_names", "novel_structure", "novel_composition")
    out = ["| Arm | Family | " + " | ".join(slices) + " |", "|---|---|" + "---:|" * len(slices)]
    for arm in arms:
        for family in FAMILIES:
            by = summary.get(arm, {}).get(family, {}).get("frozen", {}).get("by_slice")
            if by:
                out.append(
                    f"| `{arm}` | {family} | "
                    + " | ".join(f"{by.get(s, float('nan')):.3f}" for s in slices)
                    + " |"
                )
    return out


def selected_budgets(stage: dict[str, Any]) -> list[str]:
    out = ["| Arm | Core width | Trainable | Rate | Epochs |", "|---|---:|---:|---:|---:|"]
    for name, arm in stage["arms"].items():
        out.append(
            f"| `{name}` | {arm['hidden']} | {arm['parameters']['trainable_parameters']} | "
            f"{arm['learning_rate']} | {arm['epochs']} |"
        )
    return out


def render() -> str:
    lines = [
        "# `aaa.python.v1` development report",
        "",
        "Generated by `tools/write_aaa_python_v1_report.py` from retained evidence; do not edit by hand.",
        "",
        "**Status: development evidence.** Not confirmation, not a capability claim. Intervals are crossed",
        "bootstraps over initializations and streams (10 x 30 cells of 40 tasks unless stated). A sign is",
        "reported only when the 95% interval excludes zero; Holm adjusts across the five families of each",
        "primary contrast. `DEGENERATE` means the two arms never disagreed on any task.",
        "",
        "## Evidence files",
        "",
    ]
    for stage in STAGES:
        path = EVIDENCE / f"stage_{stage}.json"
        if path.is_file():
            doc = json.loads(path.read_text(encoding="utf-8"))
            src = doc["provenance"]["source"]
            lines.append(
                f"- `{path.relative_to(ROOT)}` sha256 `{sha(path)[:16]}...`, commit `{src['commit'][:12]}` "
                f"(dirty: {src['dirty']}), phase fingerprint `{src['phase_fingerprint'][:12]}...`, "
                f"{doc['wall_seconds']:.0f} s"
            )
    encoders = load("encoders")
    if encoders:
        st = encoders["stage"]
        lines += ["", "## 1. Encoders at matched capacity (one-hot heads)", ""]
        lines += selected_budgets(st)
        arms = [a for a in st["summary"]["arms"] if a.startswith(("lin@", "h16@"))]
        lines += ["", "Frozen evaluation accuracy:", "", *arm_table(st, arms)]
        base = [
            "uniform",
            "majority",
            "lookup",
            "v0_heuristic",
            "rules",
            "medoid",
            "visible_tests",
            "v0_instrument",
        ]
        lines += [
            "",
            "Baselines and the unmodified v0 instrument on the same streams:",
            "",
            *arm_table(st, base),
        ]
        lines += ["", "Contrasts:", "", *contrast_table(st)]
        lines += ["", "Frozen accuracy by slice:", "", *slice_table(st, ["h16@e1", "h16@e2"])]
    heads = load("heads")
    if heads:
        st = heads["stage"]
        lines += ["", f"## 2. Heads (encoder `{st['selections']['encoder']}`, 16-unit core)", ""]
        lines += [*selected_budgets(st), "", *arm_table(st, list(st["arms"])), "", *contrast_table(st)]
    capacity = load("capacity")
    if capacity:
        st = capacity["stage"]
        sel = st["selections"]
        lines += [
            "",
            f"## 3. Capacity (encoder `{sel['encoder']}`, output `{sel['output_head']}`, localize `{sel['localize_head']}`)",
            "",
        ]
        lines += [
            *selected_budgets(st),
            "",
            "Frozen evaluation accuracy:",
            "",
            *arm_table(st, list(st["arms"])),
        ]
        lines += ["", "Online evaluation accuracy:", "", *arm_table(st, list(st["arms"]), "online")]
        lines += ["", "Contrasts:", "", *contrast_table(st)]
        verdict = st["capacity_verdict"]
        lines += [
            "",
            f"**Declared 1K-versus-10K rule, development: `{verdict['verdict']}`.** Materially improved families:"
            f" {verdict['materially_improved'] or 'none'}; families where 10K earns its size over 4K:"
            f" {verdict['earns_over_4k'] or 'none'}; harmed: {verdict['harmed'] or 'none'}.",
        ]
    for name, title in (
        ("budget", "3b. Declared budget-extension diagnostic (64 epochs)"),
        ("optimization", "4. Optimization, one change at a time"),
        ("tool", "5. The visible-test tool (repair)"),
    ):
        doc = load(name)
        if doc:
            st = doc["stage"]
            lines += [
                "",
                f"## {title}",
                "",
                *selected_budgets(st),
                "",
                *arm_table(st, list(st["summary"]["arms"])),
            ]
            lines += ["", *contrast_table(st)]
    adapt = load("adapt")
    if adapt:
        lines += ["", "## 6. Adaptation after a distribution switch, and retention", ""]
        lines += ["Error-rate estimands (10 initializations x 15 streams, branches of 20 tasks):", ""]
        lines += [
            "| Arm | Family | Online advantage, changed | Online advantage, control | Difference of differences | Forgetting (changed) |",
            "|---|---|---|---|---|---|",
        ]
        for arm, fams in adapt["stage"]["summary"].items():
            for family in FAMILIES:
                f = fams[family]
                lines.append(
                    f"| `{arm}` | {family} | {signed(f['online_advantage_changed'])} | {signed(f['online_advantage_control'])} | "
                    f"{signed(f['difference_of_differences'])} {f['difference_of_differences']['resolved_sign']} | "
                    f"{signed(f['forgetting_after_changed'])} {f['forgetting_after_changed']['resolved_sign']} |"
                )
    plasticity = load("plasticity")
    if plasticity:
        lines += ["", "## 7. Plasticity", ""]
        lines += [
            "| Arm | Late/early learning ratio [95%] | Late - fresh | Loss of plasticity |",
            "|---|---|---|---|",
        ]
        for arm, row in plasticity["stage"]["summary"].items():
            r, g = row["late_over_early_ratio"], row["late_minus_fresh"]
            lines.append(
                f"| `{arm}` | {r['mean']:.3f} [{r['lower']:.3f}, {r['upper']:.3f}] | "
                f"{g['mean']:+.3f} [{g['lower']:+.3f}, {g['upper']:+.3f}] | {row['loss_of_plasticity']} |"
            )
        lines += [
            "",
            "| Arm | Epoch | Permuted accuracy after learning | Saturated | Dormant | Effective rank | Grad norm | Core weight norm |",
            "|---|---:|---:|---:|---:|---:|---:|---:|",
        ]
        for arm, row in plasticity["stage"]["summary"].items():
            for epoch, c in row["curve"].items():

                def fmt(v: Any) -> str:
                    return "" if v is None else f"{v:.3f}"

                lines.append(
                    f"| `{arm}` | {epoch} | {c['after_mean']:.3f} | {fmt(c['saturated_fraction'])} | {fmt(c['dormant_fraction'])} | "
                    f"{fmt(c['effective_rank'])} | {fmt(c['mean_gradient_norm_recent'])} | {fmt(c['core_weight_norm'])} |"
                )
    posthoc = load("posthoc")
    if posthoc:
        st = posthoc["stage"]
        lines += [
            "",
            "## 7b. Post-hoc diagnostic: 4K adaptation and plasticity",
            "",
            "**Post-hoc, labelled:** added after observing sections 6 and 7; part of no declared verdict. Re-running",
            "1K and 10K reproduced the committed adaptation and plasticity rows exactly.",
            "",
            "| Contrast | Difference [95%] | Sign |",
            "|---|---|---|",
        ]
        for name, row in st["contrasts"].items():
            lines.append(f"| {name} | {signed(row)} | {row['resolved_sign']} |")
        lines += [
            "",
            "| Size | Family | Difference of differences | Forgetting (changed) |",
            "|---|---|---|---|",
        ]
        for arm, fams in st["adapt_summary"].items():
            for family in FAMILIES:
                f = fams[family]
                lines.append(
                    f"| `{arm}` | {family} | {signed(f['difference_of_differences'])} "
                    f"{f['difference_of_differences']['resolved_sign']} | {signed(f['forgetting_after_changed'])} |"
                )
        lines += ["", "| Size | Late/early ratio | Late - fresh |", "|---|---|---|"]
        for arm, row in st["plasticity_summary"].items():
            r, g = row["late_over_early_ratio"], row["late_minus_fresh"]
            lines.append(
                f"| `{arm}` | {r['mean']:.3f} [{r['lower']:.3f}, {r['upper']:.3f}] | "
                f"{g['mean']:+.3f} [{g['lower']:+.3f}, {g['upper']:+.3f}] |"
            )
    attack = load("attack")
    if attack:
        st = attack["stage"]
        lines += [
            "",
            "## 8. Attack pool (used once, development budgets, no re-tuning; 10 x 15 cells of 40 tasks)",
            "",
        ]
        lines += [*arm_table(st, list(st["summary"]["arms"])), "", *contrast_table(st)]
        lines += [
            "",
            "Frozen accuracy by slice:",
            "",
            *slice_table(st, [a for a in st["arms"] if a.startswith(("h16", "1k", "10k"))]),
        ]
    lines += [
        "",
        "## Reproduce",
        "",
        "At each file's recorded commit, with `AAA_DATA_ROOT` on the HDD:",
        "`python -m research.aaa_python_v1 develop --stage <stage> --output <json> --previous <earlier stage files>`;",
        "verify a stage's summary from its primitives with `python -m research.aaa_python_v1 summarize --evidence <json>`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        current = REPORT.read_text(encoding="utf-8") if REPORT.is_file() else ""
        if current != text:
            print("the development report is stale; regenerate it", file=sys.stderr)
            return 1
        print("development report is current")
        return 0
    REPORT.write_text(text, encoding="utf-8")
    print(f"wrote {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
