#!/usr/bin/env python3
"""Write docs/aaa_python_development_report.md from the retained aaa.python.v0 evidence.

Every number and every interpretive sentence is computed here from the
committed evidence; no sentence is static prose about a result (the
``AAA-181`` lesson). The evidence and records hashes are printed at the top.

    python tools/write_aaa_python_report.py            # write the report
    python tools/write_aaa_python_report.py --check    # fail if it is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = "docs/evidence/aaa_python_v0/development.json"
RECORDS = "docs/evidence/aaa_python_v0/development_records.jsonl.gz"
OUTPUT = "docs/aaa_python_development_report.md"
FAMILIES = ("syntax", "outcome", "output", "localize", "repair")
MAIN_ARMS = (
    "online",
    "frozen",
    "feedback_disabled",
    "reset_each_task",
    "uniform",
    "majority",
    "lookup",
    "heuristic",
)


def _sha(relative: str) -> str:
    return hashlib.sha256((ROOT / relative).read_bytes()).hexdigest()


def _interval(result: Mapping[str, Any], signed: bool = False) -> str:
    fmt = "{:+.3f}" if signed else "{:.3f}"
    if result.get("interval_status") != "MEASURED":
        return fmt.format(result["mean"]) + " (no interval)"
    return f"{fmt.format(result['mean'])} [{fmt.format(result['lower'])}, {fmt.format(result['upper'])}]"


def _count(summary: Mapping[str, Any], contrast: str, sign: str) -> list[str]:
    return [f for f in FAMILIES if summary[f]["contrasts"].get(contrast, {}).get("resolved_sign") == sign]


def _names(families: list[str]) -> str:
    return ", ".join(f"`{f}`" for f in families) if families else "none"


def render(evidence: Mapping[str, Any]) -> str:
    summary = evidence["summary"]["families"]
    provenance = evidence["provenance"]
    plan = evidence["plan"]
    lines = [
        "# `aaa.python.v0` development report",
        "",
        "Generated by `tools/write_aaa_python_report.py` from retained evidence; do not edit by hand.",
        "",
        f"- evidence `{EVIDENCE}` sha256 `{_sha(EVIDENCE)}`",
        f"- records `{RECORDS}` sha256 `{_sha(RECORDS)}` ({evidence['records']['count']} actions,"
        f" content digest `{evidence['records']['sha256']}`)",
        f"- produced at commit `{provenance['source']['commit']}` (dirty: {provenance['source']['dirty']}),"
        f" phase fingerprint `{provenance['source']['phase_fingerprint']}`, spec `{evidence['spec_sha256']}`",
        f"- CPython {provenance['interpreter']['version']} on {provenance['compute']['cpu_model']},"
        f" device `{provenance['compute']['resolved_device']}`, {provenance.get('wall_seconds')} s wall",
        f"- design: {plan['initializations']} initializations x {plan['streams']} streams x"
        f" {plan['stream_length']} tasks per family; adaptation prefix {plan['prefix']}, branches {plan['branch']};"
        f" probe bank {plan['probe_bank']}; {plan['draws']} bootstrap draws",
        "",
        "**Status: development evidence.** It is not confirmation evidence and not a capability claim.",
        "Intervals are crossed bootstraps over initializations and streams. A sign is reported only when the",
        "95% interval excludes zero.",
        "",
        "## What the evidence says",
        "",
    ]
    better_than_frozen = _count(summary, "online - frozen", "POSITIVE")
    worse_than_frozen = _count(summary, "online - frozen", "NEGATIVE")
    above_chance = _count(summary, "online - uniform", "POSITIVE")
    above_reset = _count(summary, "online - reset_each_task", "POSITIVE")
    above_majority = _count(summary, "online - majority", "POSITIVE")
    below_heuristic = _count(summary, "online - heuristic", "NEGATIVE")
    above_heuristic = _count(summary, "online - heuristic", "POSITIVE")
    adaptive = [
        f
        for f in summary
        if summary[f].get("adaptation", {}).get("difference_of_differences", {}).get("resolved_sign")
        == "POSITIVE"
    ]
    forgetting = [
        f
        for f in summary
        if any(
            summary[f].get("adaptation", {}).get(k, {}).get("resolved_sign") == "POSITIVE"
            for k in ("forgetting_after_changed", "forgetting_after_control")
        )
    ]
    hits = {f: summary[f]["arms"]["lookup"]["lookup_hit_rate"] for f in FAMILIES}
    lines += [
        f"- **Online updating beats the identical frozen learner** in {len(better_than_frozen)} of {len(FAMILIES)} families"
        f" ({_names(better_than_frozen)}); it is resolved *worse* in {_names(worse_than_frozen)}.",
        f"- **Trained knowledge transfers beyond chance** in {_names(above_chance)}, and beats the memory-disabled"
        f" control in {_names(above_reset)}. That shows the training pass changes predictions on fresh programs,"
        " not that Python semantics were learned.",
        f"- **It beats the majority baseline** in {_names(above_majority)}.",
        f"- **Simple surface heuristics beat it** in {_names(below_heuristic)}; it beats the heuristic in {_names(above_heuristic)}.",
        f"- **Adaptation** (difference of differences, resolved positive): {_names(adaptive)}.",
        f"- **Forgetting** on the never-trained probe bank (resolved positive): {_names(forgetting)}.",
        f"- **Exact-match lookup hit rate** on development tasks: {', '.join(f'{f} {hits[f]:.0%}' for f in FAMILIES)}"
        " (the split separation removes memorizable duplicates by construction).",
        "",
        f"Unresolved is not zero. These intervals come from {plan['initializations']} initializations x"
        f" {plan['streams']} streams and are wide.",
        "",
    ]
    for family in FAMILIES:
        entry = summary[family]
        lines += [
            f"## `{family}`",
            "",
            "| Arm | Accuracy [95%] | Balanced | Brier | ECE | Updates |",
            "|---|---|---:|---:|---:|---:|",
        ]
        arms = [a for a in MAIN_ARMS if a in entry["arms"]] + sorted(a for a in entry["arms"] if "@" in a)
        for arm in arms:
            row = entry["arms"][arm]
            lines.append(
                f"| `{arm}` | {_interval(row['accuracy'])} | {row['balanced_accuracy']:.3f} | {row['brier']:.3f} |"
                f" {row['expected_calibration_error']:.3f} | {row['updates']} |"
            )
        lines += ["", "| Contrast (accuracy) | Difference [95%] | Sign |", "|---|---|---|"]
        for name, result in entry["contrasts"].items():
            lines.append(f"| `{name}` | {_interval(result, signed=True)} | {result['resolved_sign']} |")
        if "adaptation" in entry:
            lines += [
                "",
                "| Adaptation and retention (error rate) | Estimate [95%] | Sign |",
                "|---|---|---|",
            ]
            for name, result in entry["adaptation"].items():
                lines.append(
                    f"| {name.replace('_', ' ')} | {_interval(result, signed=True)} | {result['resolved_sign']} |"
                )
        lines.append("")
    lines += [
        "## Reading this report",
        "",
        "- `feedback_disabled` equals `frozen` by construction; it is a pipeline control proving that no",
        "  update happens without feedback.",
        "- `online@ast_nodes` on `syntax` equals `online`: the AST representation is refused there because",
        "  the parser's verdict is the answer key (`AAA-184`), and it falls back to `lexical`.",
        "- The `output` family treats printed integers as 101 classes; two thirds of the learner's",
        "  153,600 parameters are that head.",
        "- Reproduce: `python -m research.aaa_python develop --output <json> --records <jsonl.gz>` at the",
        "  recorded commit; verify: `python -m research.aaa_python recompute --evidence",
        f"  {EVIDENCE} --records {RECORDS}`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    evidence = json.loads((ROOT / EVIDENCE).read_text(encoding="utf-8"))
    text = render(evidence)
    target = ROOT / OUTPUT
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT} is stale; run tools/write_aaa_python_report.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT} matches the evidence")
        return 0
    target.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
