"""Generate a concise report from measured run artifacts."""

from __future__ import annotations

import json
from pathlib import Path
from statistics import stdev
from typing import Any


def _fmt(value: Any, digits: int = 4) -> str:
    if value is None:
        return "not available"
    if isinstance(value, float):
        if value != 0.0 and abs(value) < 10 ** (-digits):
            return f"{value:.2e}"
        return f"{value:.{digits}f}"
    return str(value)


def _metric(summary: dict[str, object], experiment: str, predictor: str, key: str) -> Any:
    return summary["experiments"][experiment]["predictors"][predictor][key]


def _seed_mae_sd(summary: dict[str, object], experiment: str, predictor: str) -> float:
    values = [
        seed_info["predictors"][predictor]["mae"]
        for seed_info in summary["experiments"][experiment]["seeds"].values()
    ]
    return stdev(values) if len(values) > 1 else 0.0


def write_experiment_report(path: str | Path, summary: dict[str, object]) -> None:
    path = Path(path)
    learning = summary["experiments"]["learning_from_scratch"]
    frozen = summary["experiments"]["frozen_generalization"]
    adaptation = summary["experiments"]["online_adaptation"]
    lines = [
        "# AAA — Accurate Autonomous Adaptation",
        "",
        "*Measured local experiment report generated by the AAA runner for Cinqic.*",
        "",
        "## Hypothesis",
        "",
        "A small online linear predictor using only a short history of observed positions can improve with experience, generalize to new deterministic motion episodes, and contribute to recovery after an unannounced speed change.",
        "",
        "The three claims are evaluated separately. A result for one claim is not treated as proof of the others.",
        "",
        "## Method",
        "",
        f"- Run ID: `{summary['run_id']}`",
        f"- Learning rate selected on development seeds: `{_fmt(summary['dev_selection']['selected_learning_rate'])}`",
        f"- World configuration: `{json.dumps(summary['config']['world'], sort_keys=True)}`",
        f"- Development seeds: `{summary['config']['dev_seeds']}`",
        f"- Training seeds: `{summary['config']['training_seeds']}`",
        f"- Final evaluation seeds: `{summary['config']['final_seeds']}`",
        "- Predictors: persistence, most-recent-displacement constant motion, and an online linear displacement model.",
        "- Scored steps begin after four observations. Each scored iteration predicts, records the prediction, advances the world, reveals and scores the outcome, then updates enabled models.",
        "",
        "The model input is `[1, x[t-3], x[t-2], x[t-1], x[t]]`; it predicts the next displacement and adds it to `x[t]`. The update is one-example gradient descent on one half of squared displacement error. The canonical checkpoint retains weights across training episodes and was frozen for the generalization comparison.",
        "",
        "## Results",
        "",
        "### Learning from scratch",
        "",
        "Overall MAE over all training transitions:",
        "",
        "| Predictor | MAE | Episode MAE mean | Episode MAE SD |",
        "|---|---:|---:|---:|",
    ]
    for predictor in ("persistence", "constant_motion", "linear_online"):
        lines.append(
            f"| {predictor} | {_fmt(_metric(summary, 'learning_from_scratch', predictor, 'mae'))} | {_fmt(_metric(summary, 'learning_from_scratch', predictor, 'episode_mae_mean'))} | {_fmt(_metric(summary, 'learning_from_scratch', predictor, 'episode_mae_sd'))} |"
        )
    lines.extend(
        [
            "",
            "Early versus late thirds of each seed's ordered training transitions:",
            "",
            "| Predictor | Early MAE mean ± SD | Late MAE mean ± SD | Late − early |",
            "|---|---:|---:|---:|",
        ]
    )
    for predictor in ("persistence", "constant_motion", "linear_online"):
        early_late = learning["early_late"][predictor]
        lines.append(
            f"| {predictor} | {_fmt(early_late['early_mae_mean'])} ± {_fmt(early_late['early_mae_sd'])} | {_fmt(early_late['late_mae_mean'])} ± {_fmt(early_late['late_mae_sd'])} | {_fmt(early_late['late_minus_early_mean'])} |"
        )
    lines.extend(
        [
            "",
            "A negative late-minus-early value indicates lower error late in training. These values summarize learning on the training split and do not establish generalization.",
            "",
            "### Frozen generalization",
            "",
            "The final-seed episodes use unfamiliar initial states and speeds from the documented evaluation sampler. The linear checkpoint was not updated during this stage: `checkpoint_weights_unchanged` is `" + str(summary["frozen_integrity"]["checkpoint_weights_unchanged"]) + "`.",
            "",
            "| Predictor | Overall MAE | Seed MAE SD | Bounce MAE | Non-bounce MAE |",
            "|---|---:|---:|---:|---:|",
        ]
    )
    for predictor in ("persistence", "constant_motion", "linear_frozen"):
        lines.append(
            f"| {predictor} | {_fmt(_metric(summary, 'frozen_generalization', predictor, 'mae'))} | {_fmt(_seed_mae_sd(summary, 'frozen_generalization', predictor))} | {_fmt(_metric(summary, 'frozen_generalization', predictor, 'bounce_mae'))} | {_fmt(_metric(summary, 'frozen_generalization', predictor, 'non_bounce_mae'))} |"
        )
    lines.extend(
        [
            "",
            "### Online adaptation",
            "",
            "The frozen and online copies started from the same checkpoint and saw the same changed-motion trajectory as each other and as the fixed baselines. The change label is evaluator metadata and was not given to any predictor.",
            "",
            "| Predictor | Overall MAE | Seed MAE SD | Post-change-window MAE | Recovery episodes | Mean recovery steps |",
            "|---|---:|---:|---:|---:|---:|",
        ]
    )
    for predictor in ("persistence", "constant_motion", "linear_frozen", "linear_online"):
        lines.append(
            f"| {predictor} | {_fmt(_metric(summary, 'online_adaptation', predictor, 'mae'))} | {_fmt(_seed_mae_sd(summary, 'online_adaptation', predictor))} | {_fmt(_metric(summary, 'online_adaptation', predictor, 'post_change_window_mae_mean'))} | {_fmt(_metric(summary, 'online_adaptation', predictor, 'recovery_recovered_episodes'))} / {_fmt(_metric(summary, 'online_adaptation', predictor, 'recovery_applicable_episodes'))} | {_fmt(_metric(summary, 'online_adaptation', predictor, 'recovery_time_steps_mean'))} |"
        )
    lines.extend(
        [
            "",
            "## Evidence assessment",
            "",
            "- Implementation correctness is supported by the focused tests, deterministic run artifacts, and the completed unattended stages.",
            f"- Improvement with experience is not supported by this run for the linear model: its late-minus-early training MAE is `{_fmt(learning['early_late']['linear_online']['late_minus_early_mean'])}`, so late error is higher rather than lower on average.",
            f"- Frozen generalization is measurable, but the trained linear model does not beat either baseline here: its MAE is `{_fmt(_metric(summary, 'frozen_generalization', 'linear_frozen', 'mae'))}` versus `{_fmt(_metric(summary, 'frozen_generalization', 'persistence', 'mae'))}` for persistence and `{_fmt(_metric(summary, 'frozen_generalization', 'constant_motion', 'mae'))}` for constant motion.",
            f"- Continued updates help relative to the matched frozen copy in this changed-motion protocol: online post-change-window MAE is `{_fmt(_metric(summary, 'online_adaptation', 'linear_online', 'post_change_window_mae_mean'))}` versus `{_fmt(_metric(summary, 'online_adaptation', 'linear_frozen', 'post_change_window_mae_mean'))}`. This is evidence for contribution from updates in this setup, not a general adaptation claim.",
            "- The model does not beat the constant-motion baseline in any of the headline comparisons. The recovery criterion was not applicable for the reported episodes because no predictor had a sufficiently large post-change increase under the pre-declared threshold; this is reported as not applicable rather than as a fabricated recovery time.",
            "",
            "## Interpretation",
            "",
            "This implementation demonstrates that the unattended observation/prediction/scoring/update loop runs and that the linear model can be measured as it learns. Frozen performance on new episodes is the evidence relevant to generalization. The frozen-versus-online comparison is the evidence relevant to whether continued parameter updates add value after a change.",
            "",
            "A learned predictor losing to a baseline is a valid result. Constant-motion extrapolation is a strong rule for this deterministic world, and quick recovery by that baseline would not show that parameter updates caused adaptation. Four positions are a short observation window, not a general long-term memory system.",
            "",
            "The prototype does not establish general intelligence, understanding of physics, a novel scientific architecture, or autonomous goal formation. The motion equations, boundary rule, scenarios, and evaluation protocol are supplied by the programmer; only the linear predictor weights are updated from observed outcomes.",
            "",
            "## Reproducibility and artifacts",
            "",
            "The complete resolved configuration, package versions, local commit metadata, JSONL/CSV step logs, aggregate metrics, checkpoint, plots, and this report are in this run directory. The working-tree flag is recorded because a commit identifier alone is not a complete description when local edits are present.",
            "",
            "## Limitations and next experiment",
            "",
            "The world is one-dimensional, deterministic, and noise-free. The linear model has no explicit bounce or change detector, and the evaluation horizon can end before the recovery criterion is satisfied. The most useful next experiment is to add controlled observation noise and compare the same frozen-versus-online protocol across several noise levels, with the noise schedule fixed before the final split.",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
